spring.application.name=Demo
spring.datasource.url=jdbc:h2:mem:products
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=Shubh
spring.datasource.password=Shubh@162630

# Enable H2 Console
spring.h2.console.enabled=true
spring.jpa.show-sql=true
